@startuml Schéma conceptuel

object Repository {
	gitLink : string
}
object Branch {
	name: string
}
object Commit {
	sha : string
    date : date
    author : string
    message : string
}
object File {
	path : string
}
object Function {
    signature : string
    linePosition : number
}
object Complexity {
	value : number
}
object IdentifiableEntity {
	entity : string
}
object Duplication {
    text : string
}

Repository "1" -down-> "*" Commit : "saves"
Commit "1..*" -right-> "1..*" Branch : "describes"
Commit "1" -down-> "1..*" File : "makes version of"
"File" "1" -right-> "*" Function : "contains"
"File" "1..*" -down-> "*" IdentifiableEntity : contains
Complexity "1" -up-> "1" Function : "mesures"
"File" "1..*" -left-> "*" Duplication : "contains"

@enduml