@startuml Schéma relationnel

!define primary_key(x) <b><color:#b8861b><&key></color> x</b>
!define foreign_key(x) <color:#aaaaaa><&key></color> x
!define column(x) <color:#efefef><&media-record></color> x
!define table(x) object x << (T, white) >>
!define nullable <b><color:#098229>[N]</color></b>
!define unique <b><color:#091782>[U]</color></b>
!define pkey <b><color:#b8861b>[PK]</color></b>
!define fkey <b><color:#000000>[FK]</color></b>
!define space <b>         </b>
hide circle
skinparam classAttributeIconSize 0

table(repository) {
	primary_key(id) : String(36) pkey
    ---
    column(owner) : Text
    column(name) : Text
    column(git_link) : Text
}

table(project) {
    primary_key(id) : String(36) pkey
    ---
    foreign_key(repo_id) : String(36) fkey
    foreign_key(commit_id) : String(36) fkey
    foreign_key(file_id) : String(36) fkey
    foreign_key(function_id) : String(36) fkey
    foreign_key(identifiable_entity_id) : String(36) fkey
    foreign_key(duplication_id) : String(36) fkey
    ---
    column(branch_name) : Text
    column(date) : DateTime
}

table(commit) {
    primary_key(id) : String(36) pkey
    ---
    column(sha) : Text
    column(author) : Text
    column(message) : Text nullable
    column(total_complexity) : Integer 
    column(average_complexity) : Float
    column(function_count) : Integer
    column(todo_fixme_count) : Integer
    column(duplications_found) : Integer
}

table(file) {
    primary_key(id) : String(36) pkey
    ---
    column(name) : Text
    column(total_complexity) : Integer 
    column(average_complexity) : Float
    column(function_count) : Integer
    column(todo_fixme_count) : Integer
    column(duplications_found) : Integer
}

table(function) {
    primary_key(id) : String(36) pkey
    ---
    column(name) : Text
    column(start_line) : Integer
    column(end_line) : Integer
    column(complexity) : Integer
}

table(identifiable_entity) {
    primary_key(id) : String(36) pkey
    ---
    column(text) : Text
    column(line_position) : Integer
}

table(duplication) {
    primary_key(id) : String(36) pkey
    ---
    column(content_hash) : Text
    column(start_line) : Integer
    column(end_line) : Integer
}

project  -right-> commit : space
project  -left-> file : space
project  -down-> function : space
project  -up-> repository : space
project  -up-> duplication : space
project  -down-> identifiable_entity : space


' Référence pour la base du style: 
' Diakogiannis, A. D. (2024, March 8). Database modeling tutorial using PlantUML. JEE.gr. https://jee.gr/database-modeling-tutorial-using-plantuml/
