@startuml PMD_CPD_XmlReader
hide circle
skinparam classAttributeIconSize 0
title PMD_CPD_XmlReader



class "<<Abstract>>\nDuplicationReportReaderInterface" as DuplicationReportReaderInterface {
    + read(text): list<DuplicationReport>
}

class PMD_CPD_XmlReader {
    - directory : str
    + ctor(repo_path)
    - read_report(xmlNode) : DuplicationReport
    + read(text) : list<DuplicationReport>
}

enum "<<Enum>>\nPMD_CPD_XMLTag" as PMD_CPD_XMLTag {
    DUPLICATION_TAG
    FILE_TAG
    CODE_FRAGMENT_TAG
}

class DuplicationReport {
    - lines : int
    - fragment : str
    - files : list<DuplicationReport.File>
    + ctor(lines, fragment)
    + add_file(file)
    + get_lines() : int
    + get_fragment() : str
    + get_file_nb() : int
}

class "DuplicationReport.File" as DRFile {
    + filename : str
    + lines : ValueRange
    + columns : ValueRange
    + ctor(filename, lines, columns)
}

DuplicationReport o-right- DRFile
PMD_CPD_XmlReader .left.|> DuplicationReportReaderInterface : "Implémente"
PMD_CPD_XmlReader -right-> PMD_CPD_XMLTag
PMD_CPD_XmlReader --> DuplicationReport

@enduml