@startuml duplication_emballage
hide circle
skinparam classAttributeIconSize 0
title Classe emballage (Wrapper) 

class "<<Abstract>>\nDuplicationToolInterface" as DuplicationToolInterface {
    + run(languages, directory): list<str>
}

enum "<<Enum>>\nPMD_CopyPasteDetector.Language" as PMD_CPD_Language {
    PYTHON = "python"
}

class PMD_CopyPasteDetector {
    - minimum_tokens : int
    - languages : list<enum>
    - directory : str

    + ctor(minimum_tokens) 
    + run(languages, directory) : list<str>
}

PMD_CopyPasteDetector -up-|> DuplicationToolInterface : "Implémente"
PMD_CopyPasteDetector -right-> PMD_CPD_Language

class "<<Abstract>>\nDuplicationReportReaderInterface" as DuplicationReportReaderInterface {
    + read(): list<DuplicationReport>
}

class PMD_CPD_XmlReader {
    - reports : list<DuplicationReport>
    - directory : str
    + ctor(directory)
    - read_file(xmlNode, report)
    - read_code_fragment(xmlNode, report)
    - read_duplication(xmlNode)
    + read(text) : list<DuplicationReport>
}

PMD_CPD_XmlReader -up-> DuplicationReportReaderInterface

@enduml